<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/16
 * Time: 20:48
 */

namespace app\admin\controller;

use think\Session;

class Index extends Common
{

    /**
     * 初始化页面
    */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 首页
    */
    public function index()
    {
        $user_id = Session::get( config('USER_AUTH_KEY') );
        if (!$user_id) {
            $this->redirect('index/login');
        }
    }

    /**
     * 登录页
    */
    public function login()
    {
        return view();
    }

}