<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/16
 * Time: 20:48
 */

namespace app\admin\controller;


class Index extends Common
{

    /**
     * 初始化页面
    */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录页
    */
    public function login()
    {
        return view();
    }

}