<?php
namespace app\index\controller;

class Index extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('css_list', ['index']);
    }

    public function index()
    {
        return view();
    }
}
